const fs = require('fs');
const path = require('path');
const { spawn, execSync } = require('child_process');

// --- 1. 設定路徑 ---
const CONFIG_PATH = path.join(__dirname, 'electron/setting/config.json');

// 後端路徑
const BACKEND_DIR = path.join(__dirname, 'electron/simulation/stats');
const BACKEND_REGISTRY = path.join(BACKEND_DIR, 'registry.ts');

// 前端路徑
const FRONTEND_DIR = path.join(__dirname, 'src/components/reports');
const FRONTEND_REGISTRY = path.join(FRONTEND_DIR, 'index.ts');

// 模板路徑
const TPL_DIR = path.join(__dirname, 'templates');
const TPL_BACKEND = path.join(TPL_DIR, 'backend.ts.hbs');
const TPL_FRONTEND = path.join(TPL_DIR, 'frontend.vue.hbs');

// --- Helper Functions ---

function getOldContent(path) {
  if (fs.existsSync(path)) return fs.readFileSync(path, 'utf-8');
  return '';
}

// 讀取並替換模板
function renderTemplate(tplPath, data) {
  if (!fs.existsSync(tplPath)) {
    // 如果找不到外部模板，這裡可以提供一個預設的 fallback 字串，或者報錯
    console.error(`❌ Template not found: ${tplPath}`);
    return '';
  }
  let content = fs.readFileSync(tplPath, 'utf-8');
  // 簡單的替換邏輯
  for (const [key, value] of Object.entries(data)) {
    content = content.replaceAll(`{{${key}}}`, value);
  }
  return content;
}

// --- 3. 主要邏輯 ---

function generate() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.error('❌ Config file not found!');
    return;
  }

  let config;
  try {
    config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
  } catch (e) {
    console.error('❌ JSON Parse Error. Waiting for fix...');
    return;
  }

  const components = config.components || [];

  const backendImports = [];
  const backendKeys = [];
  const frontendImports = [];
  const frontendKeys = [];

  // 確保目標資料夾存在
  if (!fs.existsSync(BACKEND_DIR)) fs.mkdirSync(BACKEND_DIR, { recursive: true });
  if (!fs.existsSync(FRONTEND_DIR)) fs.mkdirSync(FRONTEND_DIR, { recursive: true });

  components.forEach(comp => {
    const { model, view } = comp;

    // --- Backend Model 處理 ---
    if (model) {
      const filePath = path.join(BACKEND_DIR, `${model}.ts`);

      // 只有檔案不存在時才建立 (避免覆蓋你寫好的邏輯)
      if (!fs.existsSync(filePath)) {
        const content = renderTemplate(TPL_BACKEND, {
          name: model,
          keyName: model.replace("StatModule", "").toLowerCase()
        });
        if (content) {
          fs.writeFileSync(filePath, content);
          console.log(`✨ [Auto-Gen] Created Backend: ${model}.ts`);
        }
      }

      // 無論檔案是否新建立，只要 config 有，就加入 Registry
      backendImports.push(`import { ${model} } from './${model}';`);
      backendKeys.push(`  '${model}': ${model},`);
    }

    // --- Frontend View 處理 ---
    if (view) {
      const filePath = path.join(FRONTEND_DIR, `${view}.vue`);

      if (!fs.existsSync(filePath)) {
        const content = renderTemplate(TPL_FRONTEND, { name: view });
        if (content) {
          fs.writeFileSync(filePath, content);
          console.log(`✨ [Auto-Gen] Created View: ${view}.vue`);
        }
      }

      frontendImports.push(`import ${view} from './${view}.vue';`);
      frontendKeys.push(`  '${view}': ${view},`);
    }
  });

  // 更新 Registry
  // 注意：這裡只會包含上方 components 迴圈中有跑到的模組
  // 如果 config.json 移除了某個模組，它就不會出現在這裡，自然就完成了「從註冊表移除」
  const backendContent = `// Auto-generated by scaffold.js\n${backendImports.join('\n')}\n\nexport const StatModuleRegistry: Record<string, any> = {\n${backendKeys.join('\n')}\n};\n`;
  const frontendContent = `// Auto-generated by scaffold.js\n${frontendImports.join('\n')}\n\nexport const ReportViewRegistry: Record<string, any> = {\n${frontendKeys.join('\n')}\n};\n`;

  if (getOldContent(BACKEND_REGISTRY) !== backendContent) {
    fs.writeFileSync(BACKEND_REGISTRY, backendContent);
    console.log('✅ Updated Backend Registry');
  }
  if (getOldContent(FRONTEND_REGISTRY) !== frontendContent) {
    fs.writeFileSync(FRONTEND_REGISTRY, frontendContent);
    console.log('✅ Updated Frontend Registry');
  }
}

// --- 4. 執行入口 ---

generate();

if (process.argv.includes('--watch')) {
  console.log('👀 [Scaffold] Watching config.json for changes...');

  fs.watchFile(CONFIG_PATH, { interval: 1000 }, (curr, prev) => {
    if (curr.mtime !== prev.mtime) {
      console.log('🔄 Config changed, checking modules...');
      generate();
    }
  });

  console.log('🚀 Starting Vite...');

  const viteProcess = spawn('npm', ['run', 'dev:vite'], { stdio: 'inherit', shell: true });

  // 🔥🔥🔥 新增：建立生命週期信號檔 🔥🔥🔥
  const SESSION_FILE = path.join(__dirname, '.dev-session');
  fs.writeFileSync(SESSION_FILE, 'running'); // 建立檔案

  let isCleaning = false;

  const cleanup = () => {
    if (isCleaning) return;
    isCleaning = true;

    console.log('🛑 Cleaning up processes...');

    // 移除信號檔 (如果是按 Ctrl+C 結束的)
    if (fs.existsSync(SESSION_FILE)) {
      try { fs.unlinkSync(SESSION_FILE); } catch (e) { }
    }

    if (viteProcess.pid) {
      if (process.platform === 'win32') {
        try {
          // 強制殺死進程樹
          execSync(`taskkill /pid ${viteProcess.pid} /f /t`, { stdio: 'ignore' });
        } catch (e) { }
      } else {
        try { process.kill(-viteProcess.pid); } catch (e) { }
      }
    }

    process.exit(0);
  };

  // 🔥🔥🔥 新增：每秒檢查信號檔是否存在 🔥🔥🔥
  // 如果檔案被 Electron 刪除了，這裡就會觸發 cleanup
  const sessionWatcher = setInterval(() => {
    if (!fs.existsSync(SESSION_FILE)) {
      console.log('🔌 Detected app closure, shutting down terminal...');
      clearInterval(sessionWatcher);
      cleanup();
    }
  }, 1000);

  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);
  process.on('exit', cleanup);
}