// Auto-generated by scaffold.js
import BaseReportView from './BaseReportView.vue';
import LineReportView from './LineReportView.vue';
import ScatterReportView from './ScatterReportView.vue';
import WildReportView from './WildReportView.vue';

export const ReportViewRegistry: Record<string, any> = {
  'BaseReportView': BaseReportView,
  'LineReportView': LineReportView,
  'ScatterReportView': ScatterReportView,
  'WildReportView': WildReportView,
};
