// Auto-generated by scaffold.js
import { BaseStatModule } from './BaseStatModule';
import { LineStatModule } from './LineStatModule';
import { ScatterStatModule } from './ScatterStatModule';
import { WildStatModule } from './WildStatModule';

export const StatModuleRegistry: Record<string, any> = {
  'BaseStatModule': BaseStatModule,
  'LineStatModule': LineStatModule,
  'ScatterStatModule': ScatterStatModule,
  'WildStatModule': WildStatModule,
};
